chain:
    bech32_prefix: penumbra
    modules:
        - actions
        - messages
        - auth
        - bank
#        - gov
#        - mint
#        - slashing
        - consensus
        - staking
#        - distribution
node:
    type: remote
    config:
        rpc:
            client_name: juno
            address: http://testnet.penumbra.zone:26657
            max_connections: 20
        grpc:
            address: testnet.penumbra.zone:8080
            insecure: true
parsing:
    workers: 8
    listen_new_blocks: true
    parse_old_blocks: true
    parse_genesis: false
    start_height: 387739
    average_block_time: 1s
#    genesis_file_path: ~/.penumbra/testnet_data/node0/tendermint/config/genesis.json

database:
    name: bdjuno
    host: 195.201.146.231
    port: 5432
    user: valik
    password: qwZX12as
    schema: public
    max_open_connections: 1
    max_idle_connections: 1
    partition_size: 100000
    partition_batch: 1000
logging:
    level: debug
    format: text
actions:
    port: 3000
telemetry:
    port: 5000




